### ISSUE TITLE
Add Integration Test to Run in CI

### ISSUE THREAD

**Issue by xanderdunn** [numerai/submission-criteria#40]
Reward: 200NMR

The current integration test, tests/integration_test.py, takes over half an hour to run on my MacBook Pro, and requires manual intervention to interpret the results.  

Instead, we need something that runs in less than a minute to test that the server's concordance and originality tests are working properly.  Add the test to run in continuous integration.

**Comment by zoso95** [comment]
I suspect that most of the bottleneck from this is coming from our classifier choices. From experience I know that the following classifiers are typically really slow - GradientBoostingClassifier, KNeighborsClassifier, AdaBoostClassifier. There might be others.

**Comment by cpurta** [comment]
@zoso95, you are correct. Running the test on my MacBook Pro with timings on fitting and predicting, GradientBoostingClassifier takes ~17 minutes to fit and KMeans took over 30 minutes to predict. I suggest that at least those classifiers be taken out of the test to reduce the time taken to ~10 minutes. The other bottle necks are the RandomForest and AdaBoost classifiers are around 4-5 minutes to fit. I have been messing around with parallelizing the fitting of models so that the test would take around 5 minutes. I can't guarantee that those times would be the same with 2 cpus on the CircleCI VM that you guys are using though.

Having this kind of test run in under a minute seems only feasible if using models that can fit and predict in under a minute which would reduce down the models to `DecisionTreeClassifier, MLPClassifier, GaussianNB, LogisticRegression`. Which thens limits the testing of how robust the originality and concordance measures are.

May be worth looking into storing the model predictions as artifacts from another build process and then having a script that pulls those models and runs the originality and concordance checks.

**Comment by xanderdunn** [comment]
Increased bounty 10 100NMR.  I'm not going to accept any outside pull requests until this is resolved because of problems like #34

**Comment by xanderdunn** [comment]
@sovaa

Bounty Sent: https://etherscan.io/tx/0xc2b107865f8378c3d7e8ee672455b1a6670557d0595dd42ee402b9706bd4db73
